project:
  type: website

website:
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://nmfs-opensci.github.io/NOAA-quarto-simple" 
  repo-url: "https://github.com/nmfs-opensci/NOAA-quarto-simple"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
      

  page-footer:
    right: "Dit is gebouwd met [Quarto](https://quarto.org/)."
  
  sidebar:
    background: "#D9E3E4"
    #logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    logo: Screenshot.png
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/Jonkman1
        text: "Harrie Jonkman op GitHUB"
  

    contents:
      - href: index.qmd
        text: Home
      - href: content/Zelf_Self/cv.qmd
        text: Zelf/Self 
      - href: content/Slim_Smart/Slim_Smart.qmd
        text: Slim/Smart 
      - href: content/Goed_Good/Goed.qmd
        text: Goed/Good 
      - href: content/Mooi_Beautiful/Mooi.qmd
        text: Mooi/Beautiful

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap

filters:
  - include-files.lua
  - quarto
  
editor: visual

